version: '3'

services:
  haproxy:
    image: haproxy
    container_name: "haproxy"
    ports:
      - 80:80
      - 9000:9000
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - default

networks:
  default:
    external: 
      name: my_network
     
# docker network create my_network --subnet 172.27.27.0/24 --ip-range 172.27.27.0/24 --gateway 172.27.27.1 
