version: '3'

services:
  apache:
    image: kujiy/php-rewrite
    ports:
      - 8001:80
    volumes:
      - ./html:/var/www/html
    networks:
      default:
        ipv4_address: 172.27.27.100    

networks:
  default:
    external: 
      name: my_network
 
     

